# Generated by Django 4.1.2 on 2023-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.FileField(upload_to="pics"),
        ),
    ]
