# Generated by Django 4.2 on 2023-04-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistinformation',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Bojack.png', null=True, upload_to=''),
        ),
    ]
