# Generated by Django 4.1.2 on 2023-04-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistinformation",
            name="cart",
        ),
    ]
