# Generated by Django 4.1.2 on 2023-05-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="stripe_product_id",
        ),
    ]
