# Generated by Django 4.2 on 2023-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistinformation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
