# Generated by Django 4.2 on 2023-04-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_name_alter_post_picture'),
        ('app', '0002_artistinformation_profile_pic'),
    ]

    operations = [
    ]
