# Generated by Django 4.2 on 2023-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artistinformation_cart_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinformation',
            name='profile_pic',
            field=models.ImageField(blank=True, default='cabbage.jpg', null=True, upload_to=''),
        ),
    ]
