# Generated by Django 4.1.3 on 2023-04-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_post_name_alter_post_picture"),
        ("app", "0002_artistinformation_profile_pic"),
    ]

    operations = []
