# Generated by Django 4.1.2 on 2023-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_post_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="stripe_product_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
