# Generated by Django 4.1.2 on 2023-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_merge_20230414_1644"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pics/"),
        ),
    ]
