# Generated by Django 4.1.2 on 2023-04-17 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="datePosted",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
