# Generated by Django 4.2 on 2023-04-25 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_artistinformation_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinformation',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/cabbage.jpg', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
