# Generated by Django 4.1.2 on 2023-04-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_artistinformation_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistinformation",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="images/cabbage.jpg", null=True, upload_to=""
            ),
        ),
    ]
