# Generated by Django 4.1.2 on 2023-04-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_post_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("customer_email", models.EmailField(max_length=254)),
                ("stripe_payment_intent", models.CharField(max_length=200)),
                ("has_paid", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.post"
                    ),
                ),
            ],
        ),
    ]
