# Generated by Django 4.1.2 on 2023-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
