# Generated by Django 4.1.2 on 2023-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="numOfArts",
            field=models.IntegerField(default=1),
        ),
    ]
