# Generated by Django 4.2 on 2023-04-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_artistinformation_profile_pic_cart'),
        ('app', '0010_post_numofarts'),
    ]

    operations = [
    ]
